// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nspeqndfwuwpfthesgdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zcGVxbmRmd3V3cGZ0aGVzZ2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2Mzk0MTUsImV4cCI6MjA1NzIxNTQxNX0.Fc9kZnMqAt5dMRTpnMLjC_TAuloJ3qApDRMuuHENVgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);